// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Account struct {
	ID          uuid.UUID `json:"id"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	AccountType string    `json:"account_type"`
}

type Isn struct {
	ID                   uuid.UUID `json:"id"`
	CreatedAt            time.Time `json:"created_at"`
	UpdatedAt            time.Time `json:"updated_at"`
	UserAccountID        uuid.UUID `json:"user_account_id"`
	Title                string    `json:"title"`
	Slug                 string    `json:"slug"`
	Detail               string    `json:"detail"`
	IsInUse              bool      `json:"is_in_use"`
	Visibility           string    `json:"visibility"`
	StorageType          string    `json:"storage_type"`
	StorageConnectionURL string    `json:"storage_connection_url"`
}

type IsnAccount struct {
	ID         uuid.UUID    `json:"id"`
	CreatedAt  sql.NullTime `json:"created_at"`
	UpdatedAt  sql.NullTime `json:"updated_at"`
	IsnID      uuid.UUID    `json:"isn_id"`
	AccountID  uuid.UUID    `json:"account_id"`
	Permission string       `json:"permission"`
}

type IsnReceiver struct {
	IsnID                      uuid.UUID `json:"isn_id"`
	CreatedAt                  time.Time `json:"created_at"`
	UpdatedAt                  time.Time `json:"updated_at"`
	MaxDailyValidationFailures int32     `json:"max_daily_validation_failures"`
	MaxPayloadKilobytes        int32     `json:"max_payload_kilobytes"`
	PayloadValidation          string    `json:"payload_validation"`
	DefaultRateLimit           int32     `json:"default_rate_limit"`
	ReceiverStatus             string    `json:"receiver_status"`
	ListenerCount              int32     `json:"listener_count"`
}

type IsnRetriever struct {
	IsnID            uuid.UUID `json:"isn_id"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
	DefaultRateLimit int32     `json:"default_rate_limit"`
	RetrieverStatus  string    `json:"retriever_status"`
	ListenerCount    int32     `json:"listener_count"`
}

type RefreshToken struct {
	HashedToken   string       `json:"hashed_token"`
	UserAccountID uuid.UUID    `json:"user_account_id"`
	CreatedAt     time.Time    `json:"created_at"`
	UpdatedAt     time.Time    `json:"updated_at"`
	ExpiresAt     time.Time    `json:"expires_at"`
	RevokedAt     sql.NullTime `json:"revoked_at"`
}

type ServiceIdentity struct {
	AccountID          uuid.UUID `json:"account_id"`
	CreatedAt          time.Time `json:"created_at"`
	UpdatedAt          time.Time `json:"updated_at"`
	ClientID           string    `json:"client_id"`
	ClientSecret       string    `json:"client_secret"`
	ClientContactEmail string    `json:"client_contact_email"`
}

type Signal struct {
	ID                 uuid.UUID       `json:"id"`
	CreatedAt          sql.NullTime    `json:"created_at"`
	AccountID          uuid.UUID       `json:"account_id"`
	SignalBatchID      uuid.UUID       `json:"signal_batch_id"`
	CorrelationID      uuid.UUID       `json:"correlation_id"`
	SignalTypeID       uuid.UUID       `json:"signal_type_id"`
	LocalRef           string          `json:"local_ref"`
	VersionNumber      int32           `json:"version_number"`
	IsLatest           bool            `json:"is_latest"`
	IsWithdrawn        bool            `json:"is_withdrawn"`
	IsArchived         bool            `json:"is_archived"`
	JsonValidityStatus string          `json:"validation_status"`
	JsonPayload        json.RawMessage `json:"json_payload"`
}

type SignalBatch struct {
	ID          uuid.UUID    `json:"id"`
	CreatedAt   sql.NullTime `json:"created_at"`
	UpdatedAt   sql.NullTime `json:"updated_at"`
	IsnID       uuid.UUID    `json:"isn_id"`
	AccountID   uuid.UUID    `json:"account_id"`
	IsLatest    bool         `json:"is_latest"`
	AccountType string       `json:"account_type"`
}

type SignalType struct {
	ID        uuid.UUID `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	IsnID     uuid.UUID `json:"isn_id"`
	Slug      string    `json:"slug"`
	SchemaURL string    `json:"schema_url"`
	ReadmeURL string    `json:"readme_url"`
	Title     string    `json:"title"`
	Detail    string    `json:"detail"`
	SemVer    string    `json:"sem_ver"`
	Stage     string    `json:"stage"`
}

type User struct {
	AccountID      uuid.UUID `json:"account_id"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
	Email          string    `json:"email"`
	HashedPassword string    `json:"hashed_password"`
	UserRole       string    `json:"user_role"`
}
